### ISSUE TITLE
Add automatic invite link gathering

### ISSUE THREAD

**Issue by BjoernPetersen** [preparingforexams/hhh-diff-bot#52]
If the bot is an administrator with the appropriate rights, it can create and export invite links: https://core.telegram.org/bots/api#createchatinvitelink

The old method should still be possible in case someone doesn't want to make the bot an admin.

**Comment by torbencarstens** [comment]
I wasn't aware that this is possible

**Comment by torbencarstens** [comment]
I'd say the chat admin should need to enable this manually though since there are groups which aren't (and shouldn't be) exposed in the listing.

**Comment by BjoernPetersen** [comment]
Well the chat admin needs to actively make the hhhdiffbot an admin, so there's that

**Comment by BjoernPetersen** [comment]
I think the possibility of doing this at all is relatively new

**Comment by torbencarstens** [comment]
Yes, but I'm guessing that most users won't be aware of this fact and might just make the hhhdiffbot an admin based on a request from someone else.

I'd be more comfortable with an explicit command (in general).

I'd say we can make a poll in HHH though where we ask the users how this should work by default.

**Comment by BjoernPetersen** [comment]
Sure

**Comment by torbencarstens** [comment]
I've opened a poll which will decide this, I'll leave it open until tomorrow.
