### ISSUE TITLE
Delete main_id from state

### ISSUE THREAD

**Issue by torbencarstens** [preparingforexams/hhh-diff-bot#62]
Superfluous since the last PR (admin id's from env)

**Comment by BjoernPetersen** [comment]
It's `null` anyway, but yeah.

**Comment by torbencarstens** [comment]
```bash
$ git pull
Already up to date.
$ grep -R main_id
$ 
```

I can only assume that this is gone already

**Comment by torbencarstens** [comment]
oh, I guess this was about the state.json file, whatever :shrug:
