### ISSUE TITLE
Set a group picture for groups without one

### ISSUE THREAD

**Issue by torbencarstens** [preparingforexams/hhh-diff-bot#88]
Do this on joining or on group picture removal

Use group name as search and use first result

**Comment by BjoernPetersen** [comment]
We should also investigate whether there are stupid AI solution that will generate a group picture based on the name, preferably free.

**Comment by torbencarstens** [comment]
Closed by d3cb95114f8eebdd9d8a21e7d2a6c2c22a2a5ff6

image search api: https://learn.microsoft.com/en-us/bing/search-apis/bing-image-search/how-to/get-images
query pararms: https://learn.microsoft.com/en-us/bing/search-apis/bing-image-search/reference/query-parameters
